version: "1.0"

services:
  mysqldb:
    image: mysql:8.0
    container_name: project_tomcat_mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./sql/config.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql
    ports:
      - "3308:3306"
    expose:
      - 3308
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=project_tomcat

  app:
    container_name: project_tomcat
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=project_tomcat
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - SECURITY_STRING=89qp134i
      - APP_NAME=app
    ports:
      - 80:8080
    expose:
      - 80
    stdin_open: true
    tty: true

volumes:
  db:
